<?php

declare(strict_types=1);

namespace App\Services;

use App\Exceptions\ExceptionHandler;
use App\Helpers\CookieConsent;
use App\Jobs\SendMetaConversionEventJob;
use App\Models\Lead;
use App\Services\GoogleAnalytics\GoogleAnalyticsService;
use App\Services\LinkedIn\LinkedInService;
use App\Services\Meta\MetaPixelUserDataFactory;
use Combindma\FacebookPixel\Facades\MetaPixel;
use Illuminate\Http\Request;

class LeadService
{
    /**
     * Create a new lead and fire tracking events.
     *
     * The Meta Pixel `eventId` is generated by the browser before submitting
     * and re-used by the Conversions API call below — same id on both channels
     * lets Meta de-duplicate the two firings.
     *
     * @param  array<string, mixed>  $attributes
     */
    public function createAndTrack(
        array $attributes,
        Request $request,
        string $metaEventId,
        string $gaEventName = 'generate_lead',
    ): Lead {
        $lead = Lead::create($attributes);

        $this->trackMetaPixelEvent(
            'Lead',
            $metaEventId,
            $attributes['email'] ?? null,
            $attributes['phone'] ?? null,
            $attributes['first_name'] ?? null,
            $attributes['last_name'] ?? null,
        );
        $this->trackGAEvent($request, $gaEventName);
        $this->trackLinkedInEvent($request, 'lead', $attributes['email'] ?? null);

        return $lead;
    }

    /**
     * Mirror a browser-side Meta Pixel event onto the Conversions API using
     * the event id generated by the browser, so Meta can de-duplicate them.
     */
    public function trackMetaPixelEvent(
        string $eventName,
        string $eventId,
        ?string $email = null,
        ?string $phone = null,
        ?string $firstName = null,
        ?string $lastName = null,
    ): void {
        if (! MetaPixel::isEnabled() || ! CookieConsent::hasMarketingConsent()) {
            return;
        }

        try {
            SendMetaConversionEventJob::send(
                $eventName,
                $eventId,
                MetaPixelUserDataFactory::make($email, $phone, $firstName, $lastName),
            );
        } catch (\Exception $e) {
            ExceptionHandler::handle($e);
        }
    }

    /**
     * Track a Google Analytics event and flash it for the next page view.
     */
    public function trackGAEvent(Request $request, string $eventName): void
    {
        GoogleAnalyticsService::trackGenerateLead($request);
        GoogleAnalyticsService::flashEvent($eventName);
    }

    /**
     * Send a server-side LinkedIn conversion event and flash it for the browser.
     */
    public function trackLinkedInEvent(Request $request, string $conversionType, ?string $email = null): void
    {
        LinkedInService::trackConversion($request, $conversionType, $email);
        LinkedInService::flashEvent($conversionType);
    }
}
