<?php

declare(strict_types=1);

namespace App\Services;

use App\Exceptions\ExceptionHandler;
use App\Helpers\CookieConsent;
use App\Models\Lead;
use App\Services\GoogleAnalytics\GoogleAnalyticsService;
use App\Services\LinkedIn\LinkedInService;
use App\Services\Meta\MetaPixelUserDataFactory;
use Combindma\FacebookPixel\Facades\MetaPixel;
use FacebookAds\Object\ServerSide\CustomData;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class LeadService
{
    /**
     * Reserved key used in the Meta Pixel flash payload to tell the browser
     * pixel whether to call fbq('track', ...) or fbq('trackCustom', ...).
     */
    public const META_TRACK_METHOD_KEY = '_meta_track_method';

    /**
     * Create a new lead and fire tracking events.
     *
     * @param  array<string, mixed>  $attributes
     */
    public function createAndTrack(array $attributes, Request $request, string $gaEventName = 'generate_lead'): Lead
    {
        $lead = Lead::create($attributes);

        $this->trackMetaPixelEvent(
            'Lead',
            $attributes['email'] ?? null,
            $attributes['phone'] ?? null,
        );
        $this->trackGAEvent($request, $gaEventName);
        $this->trackLinkedInEvent($request, 'lead', $attributes['email'] ?? null);

        return $lead;
    }

    /**
     * Send a server-side Meta Pixel event and flash it for the browser pixel.
     *
     * Both browser and server share the same UUID event id, so Meta can
     * de-duplicate the two firings. Email/phone are hashed by the Facebook
     * Business SDK before being sent to the Conversions API.
     */
    public function trackMetaPixelEvent(
        string $eventName,
        ?string $email = null,
        ?string $phone = null,
        bool $isCustomEvent = false,
    ): void {
        if (! MetaPixel::isEnabled() || ! CookieConsent::hasMarketingConsent()) {
            return;
        }

        $eventId = Str::uuid()->toString();

        try {
            MetaPixel::send(
                $eventName,
                $eventId,
                new CustomData,
                MetaPixelUserDataFactory::make($email, $phone),
            );
        } catch (\Exception $e) {
            ExceptionHandler::handle($e);
        }

        $flashPayload = $isCustomEvent
            ? [self::META_TRACK_METHOD_KEY => 'trackCustom']
            : [];

        MetaPixel::flashEvent($eventName, $flashPayload, $eventId);
    }

    /**
     * Send a server-side Meta CAPI event using an event id generated by the
     * browser pixel — used when the browser fires the pixel inline (e.g.
     * StartQuiz on first interaction) and we need the matching CAPI event
     * with the same event id to enable de-duplication.
     */
    public function trackMetaPixelEventServerSide(
        string $eventName,
        string $eventId,
        ?string $email = null,
        ?string $phone = null,
    ): void {
        if (! MetaPixel::isEnabled() || ! CookieConsent::hasMarketingConsent()) {
            return;
        }

        try {
            MetaPixel::send(
                $eventName,
                $eventId,
                new CustomData,
                MetaPixelUserDataFactory::make($email, $phone),
            );
        } catch (\Exception $e) {
            ExceptionHandler::handle($e);
        }
    }

    /**
     * Track a Google Analytics event and flash it for the next page view.
     */
    public function trackGAEvent(Request $request, string $eventName): void
    {
        GoogleAnalyticsService::trackGenerateLead($request);
        GoogleAnalyticsService::flashEvent($eventName);
    }

    /**
     * Send a server-side LinkedIn conversion event and flash it for the browser.
     */
    public function trackLinkedInEvent(Request $request, string $conversionType, ?string $email = null): void
    {
        LinkedInService::trackConversion($request, $conversionType, $email);
        LinkedInService::flashEvent($conversionType);
    }
}
