services:
    laravel.test:
        build:
            context: "./docker/8.5"
            dockerfile: Dockerfile
            args:
                WWWGROUP: "${WWWGROUP}"
        image: "sail-8.5/app"
        container_name: coine-app
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
        environment:
            PHP_IDE_CONFIG: "serverName=coine.localhost"
            WWWUSER: "${WWWUSER}"
            LARAVEL_SAIL: 1
            XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
            XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
            IGNITION_LOCAL_SITES_PATH: "${PWD}"
        volumes:
            - ".:/var/www/html"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.coine.rule=Host(`coine.localhost`)"
            - "traefik.http.routers.coine.entrypoints=web"
            - "traefik.http.services.coine.loadbalancer.server.port=80"
            - "traefik.http.services.coine.loadbalancer.healthCheck.path=/"
            - "traefik.http.services.coine.loadbalancer.healthCheck.interval=5s"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:80/"]
            interval: 10s
            timeout: 5s
            retries: 3
        networks:
            - traefik

networks:
    traefik:
        external: true
