declare global {
    interface Window {
        fbq?: (...args: unknown[]) => void;
    }
}

interface MetaPixelProps {
    eventId: string;
    pixelId: string;
    enabled: boolean;
}

/**
 * Fires a Meta Pixel browser event with an event id so the matching server-side
 * Conversions API call can be de-duplicated by Meta. Both standard events
 * (e.g. Lead, CompleteRegistration) and custom events (e.g. startQuiz) are
 * supported via the `isCustom` flag.
 */
export function trackMetaPixelEvent(
    eventName: string,
    eventId: string,
    data: Record<string, unknown> = {},
    isCustom = false,
): void {
    if (!window.fbq) {
        return;
    }

    window.fbq(isCustom ? 'trackCustom' : 'track', eventName, data, { eventID: eventId });
}

/**
 * Fires the PageView Meta Pixel browser event after every Inertia navigation,
 * using the event id generated by HandleInertiaRequests so it matches the
 * server-side PageView fired by TrackMetaPageView middleware.
 */
export function handleMetaPixelNavigation(pageProps: Record<string, unknown>): void {
    const metaPixel = pageProps.metaPixel as MetaPixelProps | undefined;
    const consent = pageProps.consent as { marketing?: boolean } | undefined;

    if (!consent?.marketing || !metaPixel?.enabled) {
        return;
    }

    trackMetaPixelEvent('PageView', metaPixel.eventId);
}
